# @package _global_

defaults:
  - /benchmark/nav/pointnav: pointnav_base
  - /habitat/dataset/pointnav: habitat_test
  - _self_

habitat:
  dataset:
    data_path: /mnt/D/MyProjects/Domestic-Robot/habitat-sim/data/datasets/pointnav/habitat-test-scenes/v1/{split}/{split}.json.gz
    scenes_dir: /mnt/D/MyProjects/Domestic-Robot/habitat-sim/data/scene_datasets/
    content_scenes: ["skokloster-castle"]
  environment:
    max_episode_steps: 500
  simulator:
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
          depth_sensor:
            width: 256
            height: 256
