# # @package _global_

# defaults:
#   - /habitat: habitat_config_base
#   - /habitat/task: pointnav
#   - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgbd_agent
#   - /habitat/dataset/pointnav: habitat_test
#   - _self_

habitat:
  seed: 7
  environment:
    max_episode_steps: 500
    iterator_options:
      shuffle: False
      group_by_scene: True
      cycle: False
  simulator:
    agents:
      agent_0:
        sim_sensors:
          rgb_sensor:
            width: 256
            height: 256
#            type: color_sensor
          depth_sensor:
            width: 256
            height: 256
    type: 'Sim-v0'
    # HABITAT_SIM_V0:
    #   GPU_DEVICE_ID: 0
    # RGB_SENSOR:
    #   WIDTH: 256
    #   HEIGHT: 256
    # DEPTH_SENSOR:
    #   WIDTH: 256
    #   HEIGHT: 256
  # task:
  #   TYPE: Nav-v0
  #   sucess_distance: 0.2

  #   SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  #   POINTGOAL_WITH_GPS_COMPASS_SENSOR:
  #     GOAL_FORMAT: "POLAR"
  #     DIMENSIONALITY: 2
  #   GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  #   measurements: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  #   SUCCESS:
  #     SUCCESS_DISTANCE: 0.2
  task:
    type: nav-v0
    sucess_distance: 0.2

    sensors: ['pointgoal_with_gps_compass_sensor']
    pointgoal_with_gps_compass_sensor:
      goal_format: "polar"
      dimensionality: 2
    goal_sensor_uuid: pointgoal_with_gps_compass

    measurements: ['distance_to_goal', 'success', 'spl']
    success:
      success_distance: 0.2
  dataset:
    type: PointNav-v1
    split: test
    data_path: /mnt/D/MyProjects/Domestic-Robot/ros_ws/src/ros_x_habitat/ros_x_habitat/data/datasets/pointnav/mp3d/v1/{split}/{split}.json.gz
    scenes_dir: /mnt/D/MyProjects/Domestic-Robot/ros_ws/src/ros_x_habitat/ros_x_habitat/data/scene_datasets/mp3d/
    content_scenes: ["2t7WUuJeko7"]

